services:
  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    command: ["server"]
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}

      # Postgres (host)
      - AUTHENTIK_POSTGRESQL__HOST=${AUTHENTIK_DB_HOST:-10.0.0.50}
      - AUTHENTIK_POSTGRESQL__PORT=${AUTHENTIK_DB_PORT:-5432}
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DB_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DB_NAME:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}

      # Redis (host)
      - AUTHENTIK_REDIS__HOST=${AUTHENTIK_REDIS_HOST:-10.0.0.50}
      - AUTHENTIK_REDIS__PORT=${AUTHENTIK_REDIS_PORT:-6379}
      - AUTHENTIK_REDIS__PASSWORD=${AUTHENTIK_REDIS_PASSWORD}

      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
      - TZ=America/Toronto
    volumes:
      - /home/jerry/infra/data/authentik/media:/media
      - /home/jerry/infra/data/authentik/custom-templates:/templates
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks: [infra_net]

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    command: ["worker"]
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}

      - AUTHENTIK_POSTGRESQL__HOST=${AUTHENTIK_DB_HOST:-10.0.0.50}
      - AUTHENTIK_POSTGRESQL__PORT=${AUTHENTIK_DB_PORT:-5432}
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DB_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DB_NAME:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}

      - AUTHENTIK_REDIS__HOST=${AUTHENTIK_REDIS_HOST:-10.0.0.50}
      - AUTHENTIK_REDIS__PORT=${AUTHENTIK_REDIS_PORT:-6379}
      - AUTHENTIK_REDIS__PASSWORD=${AUTHENTIK_REDIS_PASSWORD}

      - TZ=America/Toronto
    volumes:
      - /home/jerry/infra/data/authentik/media:/media
      - /home/jerry/infra/data/authentik/custom-templates:/templates
    restart: unless-stopped
    networks: [infra_net]

networks:
  infra_net:
    external: true
