services:
  authentik-postgres:
    image: docker.io/postgres:16
    container_name: authentik-postgres
    environment:
      - POSTGRES_DB=authentik
      - POSTGRES_USER=authentik
      - POSTGRES_PASSWORD=${AUTHENTIK_DB_PASSWORD}
    volumes:
      - /home/jerry/infra/data/authentik/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks: [infra_net]

  authentik-redis:
    image: docker.io/redis:7-alpine
    container_name: authentik-redis
    restart: unless-stopped
    networks: [infra_net]

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    depends_on:
      - authentik-postgres
      - authentik-redis
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
      - TZ=America/Toronto
    volumes:
      - /home/jerry/infra/data/authentik/media:/media
      - /home/jerry/infra/data/authentik/custom-templates:/templates
    restart: unless-stopped
    networks: [infra_net]

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    depends_on:
      - authentik-postgres
      - authentik-redis
    command: ["worker"]
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
      - TZ=America/Toronto
    volumes:
      - /home/jerry/infra/data/authentik/media:/media
      - /home/jerry/infra/data/authentik/custom-templates:/templates
    restart: unless-stopped
    networks: [infra_net]

networks:
  infra_net:
    external: true