services:
  # Alerting and reporting
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/jerry/infra/config/prometheus:/etc/prometheus
      - /home/jerry/infra/data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "7003:9090"
    restart: unless-stopped
    networks: [infra_net]

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - TZ=America/Toronto
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - /home/jerry/infra/data/grafana:/var/lib/grafana
    ports:
      - "7004:3000"
    restart: unless-stopped
    networks: [infra_net]

  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    environment:
      - TZ=America/Toronto
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST}:${POSTGRES_PORT}
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${POSTGRES_USER_GITEA}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD_GITEA}
    volumes:
      - /home/jerry/infra/data/gitea:/data
    ports:
      - "7005:3000"
      - "2222:22"
    restart: unless-stopped
    networks: [infra_net]
    
  outline:
    image: docker.io/outlinewiki/outline:latest
    container_name: outline
    restart: unless-stopped
    environment:
      - URL=http://10.0.0.50:7006
      - FORCE_HTTPS=0
      - TRUST_PROXY=1
      - DATABASE_URL=postgres://${POSTGRES_USER_OUTLINE}:${POSTGRES_PASSWORD_OUTLINE}@${POSTGRES_HOST}:${POSTGRES_PORT}/outline
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - SECRET_KEY=${OUTLINE_SECRET_KEY}
      - UTILS_SECRET=${OUTLINE_UTILS_SECRET}
    volumes:
      - outline-storage:/var/lib/outline/data
    ports:
      - "7006:3000"
    networks: [infra_net]
    
  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - "7007:9100"
    restart: unless-stopped
    networks: [infra_net]

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PAPERLESS_DBENGINE=postgresql
      - PAPERLESS_DBHOST=${POSTGRES_HOST}
      - PAPERLESS_DBPORT=${POSTGRES_PORT}
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=${POSTGRES_USER}
      - PAPERLESS_DBPASS=${POSTGRES_PASSWORD1}
      - PAPERLESS_REDIS=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_URL=${PAPERLESS_URL}
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_ADMIN_MAIL=${PAPERLESS_ADMIN_MAIL}
    volumes:
      - /home/jerry/infra/data/paperless/data:/usr/src/paperless/data
      - /home/jerry/infra/data/paperless/media:/usr/src/paperless/media
      - /home/jerry/infra/data/paperless/export:/usr/src/paperless/export
      - /home/jerry/infra/data/paperless/consume:/usr/src/paperless/consume
    ports:
      - "7008:8000"
    networks: [infra_net]
  
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - TZ=America/Toronto
      - DOMAIN=${VAULTWARDEN_DOMAIN} 
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=false
    volumes:
      - /home/jerry/infra/data/vaultwarden:/data
    ports:
      - "7009:80"
    restart: unless-stopped
    networks: [infra_net]

  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    volumes:
      - /home/jerry/infra/data/synapse:/data
    environment:
      - TZ=America/Toronto
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - SYNAPSE_REPORT_STATS=no
    command: ["run", "-c", "/data/homeserver.yaml"]
    ports:
      - "7010:8008"
    networks: [infra_net]

  element:
    image: docker.io/vectorim/element-web:latest
    container_name: element
    environment:
      - NGINX_PORT=8080
    volumes:
      - /home/jerry/infra/config/element/config.json:/app/config.json:ro
    ports:
      - "7011:8080"
    restart: unless-stopped
    networks: [infra_net]

  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
      - /home/jerry/infra/data/portainer:/data
    ports:
      - "7012:9000"
    restart: unless-stopped
    networks: [infra_net]

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - DB_HOSTNAME=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER_IMMICH}
      - DB_PASSWORD=${POSTGRES_PASSWORD_IMMICH}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /home/jerry/infra/data/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7013:2283"
    networks: [infra_net]

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-ml
    volumes:
      - /home/jerry/infra/data/immich/ml-cache:/cache
    restart: unless-stopped
    networks: [infra_net]

networks:
  infra_net:
    external: true
volumes:
  outline-storage: